### ISSUE TITLE
xframe_ignore in Kiosk mode

### ISSUE THREAD

**Issue by guysoft** [guilryder/chrome-extensions#1]
Hey,
I want enable xframe_ignore when in Kiosk mode, the reason is because of a user reporting an issue in my project here https://github.com/guysoft/FullPageOS/issues/308 

Do you have a way around that? Since the button is not available in kiosk mode.

**Comment by guilryder** [comment]
xframe_ignore should be used only **temporarily** and only for **developement, testing, or troubleshooting purposes** because it disables important browser security mechanisms (see the description of the extension in the Chrome store).

Assuming your project requires a permanent solution, the recommendation is fix your project to no longer need xframe_ignore. Showing a website full-screen should not require iframes and not require bypassing browser security mechanisms.

The bug linked shows that some of the sites listed explicitly reject iframes. xframe_ignore is not designed to disable this security mechanism permanently. Especially when it concerns government websites or login pages.
