### ISSUE TITLE
Cookie issues with sites loaded in iframes

### ISSUE THREAD

**Issue by evilantishad0w** [guilryder/chrome-extensions#13]
Looks like cookies from sites loaded in iframes may be being handled differently from sites loaded directly.  The below page loads fine when loaded directly with 3rd party cookies disabled, but failes when loaded in an iframe with your extension in place.  Loads fine with cookies opened up.

Site tested:  https://www.wunderground.com/

This may be out of scope for your simple extension but it would be nice if you or someone else could find a fix.

**Comment by guilryder** [comment]
I believe this is the expected behavior of cookies with iframes. Cookies loaded via an iframe hosted on a different domain are, by definition, third-party therefore blocked if you disable third-party cookies. The extension is not supposed to interfere with that mechanism, which is unrelated to its narrow purpose of removing `X-Frame-Options` and `Content-Security-Policy` headers.

As documented on its store page, the extension should be used only temporarily and only for development, testing, or troubleshooting purposes. In that situation, it should not be a problem to temporarily enable third-party cookies, conduct the test, then disable third-party cookies back.
